name: sleek_palette
description: An opiniated color palette.
version: 0.1.0
homepage: https://github.com/aloisdeniel/sleek_palette

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: ^2.0.11
  shared_preferences: ^0.5.6
  json_annotation: ^3.0.0
  freezed_annotation: ^0.7.1
  provider: ^4.0.4
  derived_colors: ^0.2.2 
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.2.0
  build_runner:
  freezed:  ^0.10.4
  flutter_test:
    sdk: flutter

flutter: